package com.example.Tbank_fj_2024_COURSE_PROJECT.services;

public enum UserStateEnum {
    DEFAULT, WAITING_FOR_MOVIE_TITLE, WAITING_FOR_FRIEND_USERNAME, AWAITING_MOVIE_RATING, AWAITING_MOVIE_SELECTION;
}