package com.example.Tbank_fj_2024_COURSE_PROJECT.services;

public enum UserStateEnum {
    DEFAULT_UNLOGGED,
    DEFAULT_LOGGED,
    WAITING_FOR_MOVIE_TITLE,
    WAITING_FOR_FRIEND_USERNAME,
    AWAITING_MOVIE_SELECTION_NEW,
    AWAITING_MOVIE_SELECTION_USER,
    WAITING_FOR_MOVIE_STATUS_SELECTION,
    WAITING_FOR_MOVIE_TITLE_PLANNED,
    AWAITING_PLANNED_MOVIE_SELECTION,
    WAITING_FOR_MOVIE_TITLE_WATCHED,
    AWAITING_MOVIE_RATING,
    AWAITING_MOVIE_HYPE,
    AWAITING_FRIEND_DELETION,
}