package com.example.Tbank_fj_2024_COURSE_PROJECT.telegram.services;

public enum UserStateEnum {
    DEFAULT_UNLOGGED,
    DEFAULT_LOGGED,
    WAITING_FOR_MOVIE_TITLE,
    WAITING_FOR_FRIEND_USERNAME,
    WAITING_MOVIE_SELECTION_USER,
    WAITING_WATCHED_MOVIE_NUMBER,
    WAITING_PLANNED_MOVIE_NUMBER,
    WAITING_FOR_MOVIE_STATUS_SELECTION,
    WAITING_FOR_MOVIE_TITLE_PLANNED,
    AWAITING_PLANNED_MOVIE_SELECTION,
    WAITING_FOR_MOVIE_TITLE_WATCHED,
    WAITING_MOVIE_RATING,
    WAITING_MOVIE_HYPE,
    WAITING_FRIEND_DELETION,

}